[build-system]
requires = ["scikit-build-core>=0.11", "pybind11>=3.0"]
build-backend = "scikit_build_core.build"

[project]
name = "pytart"
version = "0.1.0"
license-files = ["LICENSE"]
description="Vulkan-based GPGPU engine"
readme = "README.md"
authors = [
  { name = "cookie", email = "softcookiepp@mailfence.com" },
]
requires-python = ">=3.9"
classifiers = ["Programming Language :: Python :: 3.9"]

[project.optional-dependencies]
test = ["pytest", "numpy"]

[tool.cibuildwheel.linux]
before-build = "yum install vulkan-loader-devel.x86_64 -y"

[tool.scikit-build]
minimum-version = "build-system.requires"

# have to enable pybind cmake flag, since it can be built without python bindings too
[tool.scikit-build.cmake.define]
TART_ENABLE_PYBIND = 1
ENABLE_VALIDATION_LAYERS = 0
#TART_ENABLE_SHADER_COMPILERS = 0
#TART_ENABLE_SHARED_SHADER_COMPILERS = 0
# don't enable any of the display options; we just need headless
BUILD_WSI_XCB_SUPPORT = "OFF"
BUILD_WSI_XLIB_SUPPORT = "OFF"
BUILD_WSI_XLIB_XRANDR_SUPPORT = "OFF"
BUILD_WSI_WAYLAND_SUPPORT = "OFF"
BUILD_WSI_DIRECTFB_SUPPORT = "OFF"

[tool.scikit-build.cmake]
build-type = "Release"

[tool.pytest.ini_options]
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
log_cli_level = "INFO"
testpaths = ["tests"]

